[mypy]
python_version = 3.11
plugins = mypy_django_plugin.main

# Fail on errors
strict = True

# Ignore Django migrations (they generate dynamic code)
[mypy-*.migrations.*]
ignore_errors = True

# ------------------------
# Django settings
# ------------------------
[mypy.plugins.django-stubs]
# Point this to your Django settings module
django_settings_module = "config.settings"
