# Generated by Django 5.2.6 on 2025-10-13 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal provider name (e.g., 'openai', 'gemini', 'deepseek')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable provider name (e.g., 'OpenAI', 'Google Gemini')",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this provider is available for selection",
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        blank=True,
                        help_text="Base URL for the provider's API",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Provider",
                "verbose_name_plural": "LLM Providers",
                "db_table": "llm_providers",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal model name (e.g., 'gpt-4', 'gemini-pro')",
                        max_length=100,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable model name (e.g., 'GPT-4', 'Gemini Pro')",
                        max_length=150,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "context_window",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum context window size in tokens",
                        null=True,
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        blank=True, help_text="Maximum output tokens", null=True
                    ),
                ),
                ("supports_streaming", models.BooleanField(default=True)),
                ("supports_function_calling", models.BooleanField(default=False)),
                (
                    "cost_per_1k_input_tokens",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Cost per 1000 input tokens in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cost_per_1k_output_tokens",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Cost per 1000 output tokens in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this model is available for selection",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default model for the provider",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="llm_providers.llmprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Model",
                "verbose_name_plural": "LLM Models",
                "db_table": "llm_models",
                "ordering": ["provider__display_name", "display_name"],
                "unique_together": {("provider", "name")},
            },
        ),
    ]
