# Generated by Django 5.2.6 on 2025-10-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmmodel",
            name="cost_per_1k_input_tokens",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Cost per 1000 input tokens in USD",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="llmmodel",
            name="cost_per_1k_output_tokens",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Cost per 1000 output tokens in USD",
                max_digits=12,
                null=True,
            ),
        ),
    ]
