# Generated by Django 5.2.6 on 2025-10-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0004_api_key_security_enhancements"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apikey",
            new_name="api_keys_ap_organiz_367c67_idx",
            old_name="api_keys_or_org_created_idx",
        ),
        migrations.RenameIndex(
            model_name="apikey",
            new_name="api_keys_ap_status_ee543c_idx",
            old_name="api_keys_status_last_used_idx",
        ),
        migrations.RenameIndex(
            model_name="apikey",
            new_name="api_keys_ap_expires_f049af_idx",
            old_name="api_keys_expires_at_idx",
        ),
        migrations.RenameIndex(
            model_name="apikeyusagelog",
            new_name="api_keys_ap_api_key_02e4ae_idx",
            old_name="api_key_usage_key_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="apikeyusagelog",
            new_name="api_keys_ap_endpoin_cd774b_idx",
            old_name="api_key_usage_endpoint_idx",
        ),
        migrations.RenameIndex(
            model_name="apikeyusagelog",
            new_name="api_keys_ap_ip_addr_641890_idx",
            old_name="api_key_usage_ip_idx",
        ),
        migrations.RenameIndex(
            model_name="apikeyusagelog",
            new_name="api_keys_ap_timesta_947206_idx",
            old_name="api_key_usage_ts_idx",
        ),
    ]
