# Generated by Django 5.1.5 on 2025-08-08 18:06

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "pdf"),
                            ("docx", "docx"),
                            ("txt", "txt"),
                            ("md", "md"),
                            ("csv", "csv"),
                        ],
                        max_length=10,
                    ),
                ),
                ("size_bytes", models.PositiveIntegerField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "processing"),
                            ("ready", "ready"),
                            ("failed", "failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "upload_date"],
                name="documents_d_organiz_428f7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "name"], name="documents_d_organiz_0183dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="documents_d_documen_8ea6ce_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
    ]
