# Generated by Django 5.1.5 on 2025-08-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_d_organiz_428f7c_idx",
            old_name="doc_org_uploaddate_idx",
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_d_organiz_0183dc_idx",
            old_name="doc_org_name_idx",
        ),
        migrations.RenameIndex(
            model_name="documentchunk",
            new_name="documents_d_documen_8ea6ce_idx",
            old_name="docchunk_doc_idx",
        ),
    ]
