# Generated by Django 5.1.5 on 2025-08-08 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key_encrypted", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("revoked", "revoked")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("quota", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("full-access", "full-access"),
                            ("read-only", "read-only"),
                            ("upload-only", "upload-only"),
                        ],
                        default="full-access",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
