# Generated by Django 5.2.5 on 2025-08-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0002_apikey_key_hmac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="scope",
            field=models.CharField(
                choices=[
                    ("full-access", "Full Access"),
                    ("read-only", "Read Only"),
                    ("upload-only", "Upload Only"),
                ],
                default="full-access",
                max_length=20,
            ),
        ),
    ]
