# Generated by Django 5.2.6 on 2025-09-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        (
            "documents",
            "0002_rename_doc_org_uploaddate_idx_documents_d_organiz_428f7c_idx_and_more",
        ),
        ("organizations", "0002_organization_slug_alter_organization_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="documents_connected",
            field=models.ManyToManyField(
                blank=True,
                help_text="Documents that this chatbot can access for RAG",
                related_name="connected_chatbots",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="llm_api_key_encrypted",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="llm_is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="llm_model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="llm_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai", "OpenAI"),
                    ("gemini", "Gemini"),
                    ("deepseek", "DeepSeek"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="llm_system_prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="tone",
            field=models.CharField(
                choices=[
                    ("friendly", "Friendly"),
                    ("technical", "Technical"),
                    ("formal", "Formal"),
                    ("professional", "Professional"),
                ],
                default="technical",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatbot",
            unique_together={("organization",)},
        ),
        migrations.AddIndex(
            model_name="chatbot",
            index=models.Index(
                fields=["organization", "created_at"],
                name="chatbot_cha_organiz_2c1815_idx",
            ),
        ),
    ]
