# Generated by Django 5.2.6 on 2025-10-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_chatbot_documents_connected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="llm_api_key_encrypted",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
