# Generated by Django 5.2.5 on 2025-08-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_provider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotprovider",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="chatbotprovider",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("gemini", "Gemini"),
                    ("deepseek", "DeepSeek"),
                ],
                max_length=20,
            ),
        ),
    ]
