# Generated by Django 5.2.6 on 2025-09-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_slug_alter_organization_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="organization_logos/"
            ),
        ),
    ]
