# Generated by Django 5.2.6 on 2025-10-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_remove_organization_logo_url_organization_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
